NAME: "Dify"
VERSION: "v0.0.1"
DESC: "接入Dify应用"
META: {
  official: "https://dify.ai/",
  configuration: "https://mp.weixin.qq.com/s/YXyHYN1dC_nJAOCco7ZJjg",
  tips: "支持本地部署的Dify应用",
  fee: ""
}
# 暴露给前端的参数选项以及默认值
PARAMETERS: [
  {
    name: "api_server",
    description: "Dify API Server.",
    type: "string",
    required: false,
    choices: [
      "http://12.24.211.11/v1"
    ],
    default: "http://12.24.211.11/v1"
  },
  {
    name: "api_key",
    description: "Dify API Key.",
    type: "string",
    required: false,
    choices: [
      "app-ssU59JCzQBHrVr5EXq8ULbhg"
    ],
    default: "app-ssU59JCzQBHrVr5EXq8ULbhg"
  },
  {
    name: "username",
    description: "Dify Username.",
    type: "string",
    required: false,
    choices: [
      "唐果汁"
    ],
    default: "唐果汁"
  }
]